routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@mainOrdering');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::Resource('/articles', 'ArticlesController');
Route::get('/orderingViewed', 'ArticlesController@mostViewed')->name('ordering.mostViewed');
Route::get('/orderingLiked', 'ArticlesController@mostLiked')->name('ordering.mostLiked');
Route::get('/orderingRecommended', 'ArticlesController@recommended')->name('ordering.recommended');
Route::get('/articles/{article}', 'ArticlesController@readArticle')->name('articles.readArticle');

Route::get('/like/{article}', 'LikeController@like')->name('articles.like')->middleware('auth');
Route::get('/dislike/{article}', 'LikeController@dislike')->name('articles.dislike')->middleware('auth');

resources/views/BloggingViews/addArticle.blade.php
@extends('layouts.app')

@section('content')
    <div class="panel panel-default" align="left">
        <div class="panel-heading"><h4>New article</h4></div>
        <div class="panel-body">
            <div class="container" style="margin-top: 15px">
                <form action="{{route('articles.store')}}" method="POST">
                    {{csrf_field()}}


                    <label><h4>Article title:</h4></label>
                    <input type="text" name="title" class="form-control" style="width: 650px;" required>
                    </br>
                    </br>
                    <label><h4>Article body:</h4></label>
                    <input type="text" name="body" class="form-control" style="width: 650px;" required>
                    </br>
                    </br>

                    <input class="btn btn-info btn-md" type="submit" value="Add">

                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/BloggingViews/editArticle.blade.php
@extends('layouts.app')

@section('content')
    <div class="panel panel-default" align="left">
        <div class="panel-heading"><h4>Edit article</h4></div>
        <div class="panel-body">
            <div class="container" style="margin-top: 15px">

                <form action="{{route('articles.update',$article)}}" method="POST">
                    {{csrf_field()}}

                    <label><h4>Article title:</h4></label>
                    <input type="text" name="title" class="form-control" style="width: 650px;" value="{{$article->title}}" required>
                    </br>
                    </br>
                    <label><h4>Article body:</h4></label>
                    <input type="text" name="body" class="form-control" style="width: 650px;" value="{{$article->body}}" required>
                    </br>
                    </br>

                    <input type="hidden" name="_method" value="PUT">

                    <input class="btn btn-info btn-md" type="submit" value="Update">

                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/BloggingViews/ordering.blade.php
@extends('layouts.app')

@section('content')
    <div class="panel panel-default" align="left" style="width: 1000px">
        @if($type==0)
            <div class="panel-heading"><h4>Most viewed articles</h4></div>
        @elseif($type==1)
            <div class="panel-heading"><h4>Most liked articles</h4></div>
        @else
            <div class="panel-heading"><h4>Recommended articles</h4></div>
        @endif


        <div class="panel-body">
            <div class="container" style="margin-top: 15px">


                @foreach($articles as $article)

                    @markdown($article->title)
                    <p>@markdown(str_limit($article->body,50))</p>
                    <a href="{{route('articles.readArticle',$article)}}">Read more</a>
                    <br>
                    <label readonly>Likes: </label>
                    <input type="text" style="border: none" readonly value="{{$article->likesCounter >0 ? $article->likesCounter:'0'}}">
                    <label readonly>Views: </label>
                    <input type="text" style="border: none" readonly value="{{$article->viewsCounter }}">
                    <br>
                    <hr align="left" width="50%">

                @endforeach
                <br><br><br>
                {{$articles->links()}}
                <br><br><br><br><br>
                @if(Auth::check())
                    <a href="{{route('articles.create')}}"><h2>Add new article</h2></a>
                @endif

            </div>
        </div>
    </div>
@endsection

resources/views/BloggingViews/showArticle.blade.php
@extends('layouts.app')

@section('content')
    <div class="panel panel-default" align="left" style="width: 1000px">
        <div class="panel-heading"><h4>@markdown($article->title)</h4></div>
        <div class="panel-body">
            <div class="container" style="margin-top: 15px">
                <div style="width: 700px;">@markdown($article->body)</div>

                <br>
                <label readonly>Likes: </label>
                <input type="text" style="border: none" readonly
                       value="{{$article->likesCounter >0 ? $article->likesCounter:'0'}}">
                <br>

                @if(auth()->user())
                    @can('update',$article)
                        <form action="{{ route('articles.edit', $article) }}" method="post">
                            {{ csrf_field() }}
                            <input type="hidden" name="_method" value="GET">

                            <input class="btn btn-info btn-xs" type="submit" value="Edit">
                        </form>
                    @endcan
                    @can('delete',$article)
                        <br>
                        <form action="{{ route('articles.destroy', $article) }}" method="post">
                            {{ csrf_field() }}
                            <input type="hidden" name="_method" value="DELETE">

                            <input class="btn btn-info btn-xs" type="submit" value="Delete">
                        </form>
                    @endcan

                    @cannot('update',$article)
                        @if(\App\Models\Like::where('article_id', $article->id)->where('user_id', auth()->user()->id)->first())

                            @if(\App\Models\Like::where('article_id', $article->id)->where('user_id', auth()->user()->id)->where('type', 1)->first())
                                <a class="btn btn-default btn-xs " href="{{route('articles.like',$article)}}">Like</a>
                                <a class="btn btn-info btn-xs " href="{{route('articles.dislike',$article)}}">Dislike</a>
                            @else
                                <a class="btn btn-info btn-xs " href="{{route('articles.like',$article)}}">Like</a>
                                <a class="btn btn-default btn-xs "
                                   href="{{route('articles.dislike',$article)}}">Dislike</a>
                            @endif

                        @else
                            <a class="btn btn-info btn-xs" href="{{route('articles.like',$article)}}">Like</a>
                            <a class="btn btn-info btn-xs" href="{{route('articles.dislike',$article)}}">Dislike</a>
                        @endif
                    @endcannot
                @endif

            </div>
        </div>
    </div>

@endsection

resources/views/BloggingViews/viewArticle.blade.php
@extends('layouts.app')

@section('content')
    <div class="panel panel-default" align="left" style="width: 1000px">
        <div class="panel-heading"><h4>Articles</h4></div>
        <div class="panel-body">
            <div class="container" style="margin-top: 15px">


                @foreach($articles as $article)

                    <p style="margin-top: 30px; margin-left: 60px;">@markdown($article->title)</p>
                    <p> @markdown(str_limit($article->body, 50))</p>
                    <a class="btn btn-link btn-xs" href="{{route('articles.readArticle',$article)}}">Read more</a>
                    <hr align="left" width="50%">

                @endforeach


                <br><br><br>
                {{$articles->links()}}
                <br><br><br><br><br>
                @if(Auth::check())
                    <a href="{{route('articles.create')}}"><h2>Add new article</h2></a>
                @endif
            </div>
        </div>
    </div>

@endsection